### ISSUE TITLE
Update behavior

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#103]
I am concerned about this https://stackoverflow.com/questions/21096478/overwrite-executing-bash-script-files

If we want to execute an install which updates (as currently the case) the release clone inside trhe install dir. We need to make sure we do not execute new code introduced into scripts when currently executing the script with bash. 

I tested the update bahvior when we merge in changes and overwrite potentially executing scripts.
It **very** likely seems that git does not overwrite the existing files but replaces them
something like `rm file`  (meaning the executing script still has a handle to it)
With this beeing the case at least in Linux, we are sure we dont execute new code

**Comment by gabyx** [comment]
@matthijskooijman Do you have more insight to this?
Also this question: https://stackoverflow.com/questions/62218749/does-git-create-new-files-during-merge-or-overwrites-existing-ones

**Comment by gabyx** [comment]
Ok, this seems to work on Windows and on Linux

**Comment by matthijskooijman** [comment]
Apologies for my late reply, I was caught by some deadlines :-)

In any case, I would expect that git indeed does this "right", since recreating a new file rather than overwriting is the easiest way to atomically replace a file (e.g. you can write a new temporary file, then `mv` it over the original, and if you're interrupted, the original file is untouched). So I think it should be reasonably safe to assume that git will indeed keep doing it like this.
