### ISSUE TITLE
Global shared hooks for this repo

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#122]
@rycus: For your suggestion #119 , we might need clear notation what we mean with global shared hooks, local shared hooks and the new global shared hooks  for this repo only. 

—local is currently .shared file

—global is global githooks.shared

I am wondering how we make this CLI option. Should we keep the definition or have something like:

- checkedin shared hooks: .shared file
- local shared hooks: the global githooks.shared
- global shared hooks: the local githooks.shared

**Comment by rycus86** [comment]
In terms of CLI, I think in the https://github.com/rycus86/githooks/blob/master/docs/command-line-tool.md#git-hooks-config `git hooks config shared <url>` could maybe get a `--local` flag to only set this for the current repo.

For the logic, everything could work as-is, maybe there's some merging needed for local+global git configs for the shared repo lists. Other than that the only thing I'd want is to refuse running local (and/or `file://`) repo hooks from the `.shared` file (because someone else can update it for you).

**Comment by gabyx** [comment]
The thing is there is already a —local flag, isnt it? Which puts the url into the .shared file...

Von meinem iPhone gesendet

**Comment by rycus86** [comment]
Oh, you're right, there is. 🙈
I was only checking the cli docs and that doesn't tell about it.

Looking back now, I don't think `--local` is appropriate for changing the `.shared` file, I'd probably use `--shared` for that, then `--local` could just set the local git config variable.

**Comment by gabyx** [comment]
That would be 👌 :)

Von meinem iPhone gesendet

**Comment by gabyx** [comment]
OK, I suggest the following:

- We introduce `githooks.shared` in the local and global git config and the cli
- `git hooks shared add|remove [--local|--global] <url>` will work with the git config `githooks.shared`
- `git hooks shared add|remove [--shared] <url>` will work with the `.shared` file.

For executing hooks in `githooks.shared` or in any local/global `githooks.shared`, we track all used `SHARED_ROOT`  paths and skip if we have already executed hooks in this shared repo.

Then the executing sequence is should be now follows, (IMO):

```shell
    execute_shared_hooks "$@" || return 1 # .shared file
    execute_config_shared_hooks "$@" || return 1 # first --local git config, then --global git config
    execute_all_hooks_in "$(pwd)/.githooks" "$@" || return 1
```

**Comment by rycus86** [comment]
Sounds good to me, thanks!
