### ISSUE TITLE
Install failed when passing non-existing directory

### ISSUE THREAD

**Issue by brandonkal** [rycus86/githooks#6]
I ran the install script and attempted passing a non-existant directory.
Instead of continuing with the prompt, the install script just exited 1.

https://github.com/rycus86/githooks/blob/ad7148fa9ffd90213b5aee0d9e1bf12fb0d69c20/install.sh#L3091

**Comment by rycus86** [comment]
That bit is when you want to search for existing local repositories to install to, and it needs a *valid* root directory to start the search from.
This is because any new repositories after the first install will automatically get the Githooks plumbing scripts from the Git templates, but already existing local repos need their git hook files overwritten.

I admit we could just skip the invalid start directory and continue with the rest, but it felt safer to just bail out.
Any thoughts on the expected behaviour?

**Comment by rycus86** [comment]
Hey @brandonkal ,

Sorry it took so long, had some time off. I've pushed a change to resolve this now.
I'll try to have a look at the other issues as well.

Thanks!
